### PR TITLE
feat: ros2 camera graph

### PR DESCRIPTION
**Pull request by F1rrel**
Did a different take on the camera stream from the Isaac Sim using OmniGraphs. It uses ROS2Bridge extension, which seems to be built in C++, so it should be much better for camera data transmitting.

Created a new object class `Graph` for OmniGraphs, like this `ROS2Camera` graph. Therefore it does not create the camera sensor itself, only connects to an existing camera prim to set it up as a source for ROS2 camera topics. It uses ROS2 Camera Helper to setup the output topics. It also allows to specify camera types that will be published (rgb, depth, semantic segmentation, ...), so a camera helper will be created for each selected camera type.

The camera prim path can be local to the vehicle's prim path or global (starts with `/`). The last part of camera prim path is the camera frame id used for topics. Published topics are `/<vehicle_name>/<camera_frame_id>/<camera_type>` and `/<vehicle_name>/<camera_frame_id>/<camera_type>_labels` for labels topic.

For this I had to add `vehicle_name` to the `Vehicle` class. After finding a new free prim path for the vehicle, the last part of the vehicle's prim path (after last `/`) is used as a vehicle name (`quadrotor`). 

The `Quadrotor` class initializes the graphs right after initializing the sensors, so a new camera sensor can be added before creating a graph for it.

Added an example `8_camera_vehicle.py`, which uses the Iris Camera prim to create rgb and camera_info ROS2 Humble topics.

### CODE REVIEW

**Comment by MarceloJacinto** [comment]
Wow, this is really nice! 

Thank you for your contribution. I've been quite busy with other subjects, but I will definitely take a closer look and test this. I will try to have your features merged with the main branch maybe at the beginning of the next week.

**Comment by MarceloJacinto** [comment]
Sorry for the late reply. 

I've tested your proposal and I still get dropping frames. I'm still going to merge with the main branch as this is a nice addition and I already know how to fix this later on.

Thank you for your contribution

**Comment by F1rrel** [comment]
So, it has been half a year since the last update, is this project still alive?

I have pushed some changes to make the camera graph work with Isaac Sim 2023.1.1, currently latest version.

Also I have tested the framerate drop. With [zenoh-bridge-ros2dds](https://github.com/eclipse-zenoh/zenoh-plugin-ros2dds) acting as middleware between Isaac Sim publishers and other subscribers (Jetson connected by ethernet), the framerate was stable.

I have other parts implemented (tf, lidar, camera, odometry), so when this will get merged, I will create more PRs.

**Comment by stecf** [comment]
Updated this PR to the latest main branch, please review. Sorry it took that long.

**Comment by MarceloJacinto** [comment]
This seems to be working well in the latest version. Thank you for your contribution. I'm merging this into the main branch.

**Pull request merged**
